"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadTestConfigFileLabel = exports.loadTestResourceLabel = exports.resourceGroupLabel = exports.serviceConnectionNameLabel = exports.secretsLabel = exports.envVarsLabel = exports.outputVariableNameLabel = exports.overRideParametersLabel = exports.runDescriptionLabel = exports.testRunNameLabel = exports.loadTestConfigFile = exports.loadTestResource = exports.resourceGroup = exports.secrets = exports.envVars = exports.outputVariableName = exports.overRideParameters = exports.runDescription = exports.testRunName = void 0;
exports.testRunName = 'loadTestRunName';
exports.runDescription = 'loadTestRunDescription';
exports.overRideParameters = 'overrideParameters';
exports.outputVariableName = 'outputVariableName';
exports.envVars = 'env';
exports.secrets = 'secrets';
exports.resourceGroup = 'resourceGroup';
exports.loadTestResource = 'loadTestResource';
exports.loadTestConfigFile = 'loadTestConfigFile';
// labels user visible strings
exports.testRunNameLabel = 'Load Test Run Name';
exports.runDescriptionLabel = 'Load Test Run Description';
exports.overRideParametersLabel = 'Override Parameters';
exports.outputVariableNameLabel = 'Output Variable Name';
exports.envVarsLabel = 'env';
exports.secretsLabel = 'Secrets';
exports.serviceConnectionNameLabel = 'Azure subscription';
exports.resourceGroupLabel = 'Resource Group';
exports.loadTestResourceLabel = 'Load Test Resource';
exports.loadTestConfigFileLabel = 'Load Test Config File';
